name: SoT
version: '${project.version}'
main: com.clarkson.sot.main.SoT
api-version: '1.20' # Or your target version
depend: [WorldEdit] # Add WorldEdit dependency
author: ZacClarkson
description: A minecraft game based on MCC
commands:
  sotgetcointool:
      description: Gives the player a tool to place Coin Displays.
      usage: /<command> <value>
      permission: sot.admin.givetool
  sotsavesegment: # Add the new command
    description: Saves the selected WorldEdit region as a new SoT segment template.
    usage: /<command> <name> <type> <schematic_filename> [totalCoins]
    permission: sot.admin.savesegment # Optional: Add a permission
permissions: # Optional
  sot.admin.savesegment:
    description: Allows saving new SoT segments.
    default: op
  sot.admin.givetool:
    description: Allows getting the Coin Display placer tool.
    default: op
  sot.admin.placedisplay: # Permission checked by listener
    description: Allows placing visual coin displays for building using the tool.
    default: op