# This workflow builds a package using Maven and publishes it to GitHub Packages when a release is created.
# For more information, see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Matches the id in distributionManagement/repository of pom.xml
          settings-path: ${{ github.workspace }} # Location for the settings.xml file

      # Build the project using Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Publish the package to GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
